### ISSUE TITLE
SYNCING PACKAGES...

### ISSUE THREAD

**Issue by Abraka** [lbr38/repomanager#105] opened 2023-06-16 18:32 UTC
I updated to the latest 3.5.3 and when downloading AlmalInux repo newly predefined from list I get:
Getting repomd.xml from https://ftp.linux.cz/pub/linux/almalinux/repodata/repomd.xml ... File not found error
There is not repodata folder with repomd.xml on this mirror:
![Alma-ftpRepo1](https://github.com/lbr38/repomanager/assets/6759588/bbe3963f-a043-491f-afc3-bf6847d3371d)

Base on what was pick this specific mirror for downloading packages?

**Comment by lbr38** [comment] 2023-06-16 19:02
Hi

Ok just identified where the problem is, I will provide a fix quickly. 

But your source repo URL seems incomplete, you should use something like that:

- https://ftp.linux.cz/pub/linux/almalinux/8/AppStream/$basearch/os/ (to mirror the AppStream repository for Almalinux 8)
- https://ftp.linux.cz/pub/linux/almalinux/8/BaseOS/$basearch/os/ (to mirror the BaseOS repository for Almalinux 8)

You cannot mirror a whole RPM repository with Repomanager, you should always provide URL that contains a repodata/ directory (with the repomd.xml file inside).

But wait for my fix before retrying. The fact is that when you register a new source repo and URL, the URL is converted to lowercase which is a problem here (AppStream => appstream, returning a 404 not found because the source repository is case sensitive).

**Comment by lbr38** [comment] 2023-06-16 20:11
This should now be fixed with https://github.com/lbr38/repomanager/pull/107

**Closed** 2023-07-20 08:49 UTC
